# Generated by Django 3.2.5 on 2021-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
