# Generated by Django 3.2.5 on 2021-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0002_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_photo',
            name='image',
            field=models.ImageField(default='', upload_to='saigym/static/images'),
        ),
    ]
