# Generated by Django 3.2.5 on 2021-09-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFirstClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
