# Generated by Django 3.2.5 on 2021-09-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0005_bookfirstclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfirstclass',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
