# Generated by Django 3.2.5 on 2021-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0006_alter_bookfirstclass_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfirstclass',
            name='select',
            field=models.CharField(default='', max_length=50),
        ),
    ]
