# Generated by Django 3.2.5 on 2021-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0007_bookfirstclass_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birthplace',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
