# Generated by Django 3.2.5 on 2021-10-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0009_auto_20211002_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savecard',
            name='user',
        ),
    ]
