# Generated by Django 3.2.5 on 2021-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0011_auto_20211002_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmember',
            name='phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registeredmember',
            name='regno',
            field=models.IntegerField(default=1),
        ),
    ]
