# Generated by Django 3.2.5 on 2021-10-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0012_auto_20211002_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('phone', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('admission', models.DateTimeField(auto_now_add=True, null=True)),
                ('regno', models.IntegerField(default=1)),
                ('select', models.CharField(blank=True, max_length=20, null=True)),
                ('jan', models.CharField(blank=True, max_length=10, null=True)),
                ('feb', models.CharField(blank=True, max_length=10, null=True)),
                ('mar', models.CharField(blank=True, max_length=10, null=True)),
                ('apr', models.CharField(blank=True, max_length=10, null=True)),
                ('may', models.CharField(blank=True, max_length=10, null=True)),
                ('jun', models.CharField(blank=True, max_length=10, null=True)),
                ('july', models.CharField(blank=True, max_length=10, null=True)),
                ('aug', models.CharField(blank=True, max_length=10, null=True)),
                ('sept', models.CharField(blank=True, max_length=10, null=True)),
                ('octt', models.CharField(blank=True, max_length=10, null=True)),
                ('nov', models.CharField(blank=True, max_length=10, null=True)),
                ('dec', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='apr',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='aug',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='feb',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='jan',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='july',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='jun',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='mar',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='may',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='nov',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='octt',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='regno',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='select',
        ),
        migrations.RemoveField(
            model_name='registeredmember',
            name='sept',
        ),
    ]
