# Generated by Django 3.2.5 on 2021-10-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0015_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
