# Generated by Django 3.2.5 on 2021-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0020_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
