# Generated by Django 3.2.5 on 2021-10-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saigym', '0023_alter_diet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='authMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
